name: Build and Upload

on:
  push:
    branches:
      - main  # Change this to the branch you want to trigger the workflow on

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout source code
      uses: actions/checkout@v2

    - name: Set up Node.js (or your environment)
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Specify the Node.js version or your required environment

    - name: Install dependencies
      run: npm install  # Use your project's dependency management command

    - name: Build the project
      run: npm run build:nativebridge  # Use your project's build command

    - name: Build the core
      run: cd core && npm i && npm run build && cd ..  # Use your project's build command

    - name: Build the ios
      run: cd ios && npm i && npm run xc:build:Capacitor && npm run xc:build:CapacitorCordova && npm run xc:build:xcframework && cd ..

    - name: Build the cli
      run: cd cli && npm i && npm run build  # Use your project's build command
